const USER_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PENGAJAR: 'PENGAJAR',
  PESERTA: 'PESERTA',
};

const STATUS_USER = {
  REGISTERED: 'REGISTERED',
  ADMINISTRATION: 'ADMINISTRATION',
  WAITING: 'WAITING',
  INTERVIEWED: 'INTERVIEWED',
  REJECTED: 'REJECTED',
  ACTIVE: 'ACTIVE',
  NONACTIVE: 'NONACTIVE',
};

const TYPE_BIMBINGAN = {
  REGULER: 'REGULER',
  TAMBAHAN: 'TAMBAHAN',
};

module.exports = {
  USER_ROLE,
  STATUS_USER,
  TYPE_BIMBINGAN,
};
